version: "3.8"
services:
  
  db:
    image: mysql:oracle
    container_name: test_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql 

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db 
      MYSQL_PASSWORD: root

    ports:
      - "3306:3306"
      
    networks:
      - dev 

  phpmyadmin: 
    image: phpmyadmin
    container_name: phpymyadmin-test
    restart: always
    depends_on:
      - db
    ports: 
    - "9001:80"
    environment:
      PMA_HOST: db
    networks: 
      - dev 

networks:
  dev:

volumes:
  db-data:


